
version: "3.8"

services:
  stackedit:
    image: benweet/stackedit:latest
    container_name: stackedit
    restart: unless-stopped
    ports:
      - "3030:8080"
    volumes:
      - stackedit_data:/data
    networks:
      - highfishNetwork

  mongo:
    image: mongo:6.0
    container_name: stackedit-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - highfishNetwork

volumes:
  stackedit_data:
    driver: local
  mongo_data:
    driver: local

networks:
  highfishNetwork:
    external: true
